/* Complete, reversible page-level Chinese / English localization. */
(() => {
const EXACT = new Map([
['依据当前 index 中实际可见的工作任务、产出类型和 drawDw 分支统计；不凭 Agent 名称推测不存在的抽屉。','Based on the work tasks, output types, and drawDw branches actually visible in the current index. No drawers are inferred from Agent names.'],
['达人（KOL）Agent 的抽屉内容将作为独立模块梳理，不纳入本清单。','The Influencer (KOL) Agent drawer will be documented as a separate module and is not included here.'],
['CSS 样式请按照对应原始设计图开发，此文档仅仅做展示','Build the CSS from the corresponding source designs; this document is for demonstration only.'],
['点击 Agent 名称查看完整组件组合；点击勾选查看单个组件样式','Select an Agent name to view its full component set; select a checkmark to preview an individual component.'],
['点击查看原图片画廊 · 包含 3 种图片预览样式','Open the original image gallery · Includes three image-preview variants'],
['后续详情图生成会使用这里的产品图。此处仅限 1 张清晰参考图，以提升生成稳定性。','Future detail-page images will use this product photo. Add one clear reference image only to improve generation consistency.'],
['结构在正文之前单独确认过一次——改结构比改正文便宜得多。','The structure was approved separately before the body copy—changing the structure costs far less than rewriting the article.'],
['发布时会作为独立小节追加到正文末尾（标题按站点语言取“常见问题”或“FAQ”），所以正文预览里看不到它。','At publish time, this will be appended as a separate section at the end of the article (titled “Frequently Asked Questions” or “FAQ” according to the site language), so it does not appear in the body preview.'],
['先看配方是否精简、功效是否聚焦，再从低频率开始试用，优先选择能长期稳定使用的产品。','First check whether the formula is focused and the benefits are clear. Start with infrequent use and prioritize a product you can use consistently over time.'],
['不一定。敏感肌更需要关注成分耐受与配方协同，浓度过高反而可能增加刺激风险。','Not necessarily. Sensitive skin needs ingredient tolerance and formula balance; excessive concentrations may increase irritation.'],
['可以，但需要结合浓度与自身耐受情况。建议先局部测试，再逐步增加使用频率。','Yes, but consider the concentration and your tolerance. Patch-test first, then gradually increase usage frequency.'],
['通常建议用 3–4 周逐步观察，从隔天使用开始，根据肤感和稳定程度调整。','Allow 3–4 weeks for gradual observation. Start every other day and adjust according to comfort and skin stability.'],
['肌肤稳定后可以逐步叠加，但一次只增加一种产品，更容易判断耐受情况。','Once your skin is stable, layer products gradually. Add only one product at a time so tolerance is easier to assess.'],
['首屏以产品与核心成分作为视觉中心，用一句明确的修护主张快速建立认知。\n\n第二至第四屏依次解释敏感肌常见问题、核心成分作用与技术机制，并用实验数据支撑产品功效。\n\n后续补充适用人群、使用方法、规格信息与购买利益点，让页面从专业证据自然过渡到购买决策。','The hero screen centers the product and its key ingredient, using a clear repair claim to establish the message quickly.\n\nScreens two through four explain common sensitive-skin concerns, ingredient benefits, and the technical mechanism, supported by test data.\n\nLater screens add audience, usage, specification, and purchase-benefit information, moving naturally from professional evidence to a buying decision.'],
['预算不多的时候，我反而不会急着追新品，而是先看这 3 个真正影响使用体验的细节。\n\n一、使用频率够不够高\n买回去偶尔才用一次的产品，再便宜也是浪费。比起复杂的叠涂步骤，我更愿意留下每天都能稳定使用、早晚护肤都不费力的那一瓶。\n\n二、肤感能不能让我坚持\n吸收速度、黏腻感和后续上妆是否打架，都会决定一款产品能不能被用完。对我来说，舒服、稳定，比第一次使用时的惊艳更重要。\n\n三、它是不是解决了真实需求\n我会优先选择功能清楚、使用场景明确的产品，而不是为了凑满减堆一套暂时用不到的组合。真正适合自己的，才有长期价值。\n\n这次双十一我把预算集中在会持续使用的产品上。活动期有组合权益，但我的选择标准没有变：使用频率高、肤感舒服，也确实能坚持用完。','When my budget is limited, I do not rush after new launches. I look at three details that truly shape the experience.\n\n1. Will I use it often enough?\nEven a cheap product is wasteful if I use it only occasionally. Instead of a complicated layering routine, I prefer one bottle that works reliably every day, morning and night.\n\n2. Does it feel good enough to keep using?\nAbsorption, stickiness, and how it works under makeup determine whether I finish a product. Comfort and consistency matter more to me than a dramatic first impression.\n\n3. Does it solve a real need?\nI prioritize products with a clear function and use case instead of building a bundle just to reach a discount. The right personal fit creates lasting value.\n\nThis Singles’ Day, I focused my budget on products I will keep using. Bundle offers were available, but my criteria stayed the same: frequent use, comfortable feel, and something I can actually finish.'],
['您好，\n\n我们复核了 A80PARIS 最近 7 天的经营数据。访客数增长 12%，但支付转化率由目标 2.1% 降至 1.4%。目前更明显的信号来自移动端详情页承接：老客与自然流量的加购率也出现下降；广告新增流量意向偏弱，进一步放大了波动。\n\n建议优先检查移动端首屏加载与权益表达，并按渠道拆分做一次对照验证。我们会继续跟进变化，并在有新结论时同步。\n\n谢谢。','Hello,\n\nWe reviewed A80PARIS’s operating data for the past seven days. Visitors increased by 12%, but purchase conversion fell from the 2.1% target to 1.4%. The clearest signal is on the mobile product page: add-to-cart rates from returning customers and organic traffic also declined, while new paid traffic showed weaker intent and amplified the fluctuation.\n\nWe recommend checking mobile hero loading and offer messaging first, then running a channel-by-channel comparison. We will continue monitoring the trend and share any new findings.\n\nThank you.'],
['我先完成了 EVO 1.1 的 AI 测评，再按作息、目标和身体感受收到每日配方。AI 营养与月度优化的思路很省心，但服务跟进仍有明显落差，希望下一版配方和服务跟进能更快响应反馈。','I completed EVO 1.1’s AI assessment and received daily formulas based on my routine, goals, and how I felt. AI nutrition and monthly optimization are convenient, but service follow-up still falls short. I hope the next formula and support cycle respond to feedback faster.'],
['我先完成了 EVO 1.1 的 AI 测评，再按作息、目标和身体感受收到每日配方。能量补剂与月度优化的思路很省心，但服务跟进仍有明显落差，希望下一版配方和服务跟进能更快响应反馈。','I completed EVO 1.1’s AI assessment and received daily formulas based on my routine, goals, and how I felt. The supplement and monthly optimization approach is convenient, but service follow-up still falls short. I hope the next formula and support cycle respond to feedback faster.'],
['客服负责人为相关工单设置明确的首次响应、进度更新和关闭标准，并在社交平台私信与客服系统之间建立转交记录；每周复盘未及时跟进的案例。','Set clear first-response, progress-update, and closure standards for related support tickets. Keep handoff records between social DMs and the support system, and review delayed follow-ups weekly.'],
['净销售额明显低于预期正常水平，显示出销售异常。','Net sales are materially below the expected normal range, indicating a sales anomaly.'],
['预期依据：以近 14 天数据的中位数 1,166.05 为基准，容差 ±50%。','Expected range: based on the 14-day median of 1,166.05 with a ±50% tolerance.'],
['触达核心生活节奏快、高频点外卖及好辣好酒的中青年职场男女，确立液态孢子益生菌30分钟起效、95%胃酸存活率的初次认知。','Reach working adults with fast-paced lifestyles who often order delivery and enjoy spicy food or alcohol; introduce liquid-spore probiotics with a 30-minute onset and 95% gastric-acid survival rate.'],
['承接已被外食、嗜辣和饮酒场景内容触达的人群，强化液态孢子、30分钟起效及95%胃酸存活率等核心利益点，推动用户从场景共鸣进入功效理解。','Retarget people reached through dining-out, spicy-food, and drinking scenarios. Reinforce liquid spores, 30-minute onset, and 95% gastric-acid survival to move users from scenario affinity to benefit understanding.'],
['面向多次浏览、搜索或收藏益生菌产品的高意向人群，强化产品品质、液态剂型和便携体验，推动收藏加购并进入购买比较。','Target high-intent users who repeatedly viewed, searched, or saved probiotic products. Reinforce quality, liquid format, and portability to encourage saves, add-to-cart actions, and purchase comparison.'],
['锁定已收藏、加购或多次访问详情页的高意向人群，通过限时权益、核心功效回顾与使用场景提醒，缩短决策路径并促成最终成交。','Target high-intent users who saved, added, or repeatedly visited the product page. Use limited-time offers, benefit reminders, and usage scenarios to shorten the decision path and drive purchase.'],
['重点触达18-35岁、经常点外卖、喜爱嗜辣、生活节奏快的中青年职场男女，消费偏中高层。','Focus on 18–35-year-old working adults who frequently order delivery, enjoy spicy food, live fast-paced lives, and have mid-to-high spending power.'],
['重点覆盖25-40岁、关注肠道健康、浏览过益生菌内容但尚未形成明确品牌偏好的中高消费人群。','Focus on higher-spending adults aged 25–40 who care about gut health and have viewed probiotic content without forming a clear brand preference.'],
['重点覆盖25-45岁、近7天浏览详情页2次以上或已收藏加购、购买力L3-L5、对即时肠胃养护需求明确的高意向人群。','Focus on high-intent users aged 25–45 who visited the product page twice in seven days or saved/added it, have L3–L5 purchasing power, and clearly need immediate digestive support.'],
['重点覆盖28-45岁、近期主动搜索益生菌、关注成分与品质、具备中高购买力且已有浏览收藏行为的人群。','Focus on users aged 28–45 who recently searched for probiotics, care about ingredients and quality, have mid-to-high purchasing power, and have viewed or saved products.'],
['高端白底与深海蓝组合，产品小支装居中陈列，周围以液态流光、耐酸盾牌和便携场景构成品质证据链，突出专业、安心与随身即饮。','Combine a premium white background with deep ocean blue. Center the single-serve product and surround it with liquid light, acid-resistance shields, and portable-use scenes to convey professional quality, reassurance, and drink-anywhere convenience.'],
['蓝绿科技渐变背景，以液体孢子穿越胃酸环境的动态路径为视觉中心，结合30分钟起效与95%胃酸存活率的数据卡片，画面清晰、可信、易理解。','Use a blue-green technology gradient with the path of liquid spores through stomach acid as the visual focus. Add data cards for 30-minute onset and 95% survival for a clear, credible, easy-to-understand image.'],
['现代简约的清新蓝绿调，画面中心为外卖快餐与红辣椒视觉元素，配以流动的蓝色液滴水波，体现科技感、液体孢子的超强耐酸与速效保护感。','Use a fresh, modern blue-green palette. Center delivery food and red chili imagery with flowing blue droplets to express technology, strong acid resistance, and fast protection.'],
['现代科技感医药视觉风格，深蓝色调为主，画面右侧为举杯社交场景，左侧特写高能蓝色液滴击穿胃酸屏障、修复粘膜的过程。','Use a modern medical-technology style in deep blue. Show a social toast on the right and a close-up of an energized blue droplet crossing the stomach-acid barrier and repairing the lining on the left.'],
['以产品正装、小支装和限时权益组成强转化画面，加入外卖、聚餐、加班三个使用场景缩略图，搭配醒目的购买按钮与倒计时元素，突出现在下单的理由。','Build a conversion-focused image with full-size and single-serve products plus a limited-time offer. Add thumbnails for delivery, dining, and overtime, with a prominent buy button and countdown to create urgency.'],
['小红书活动策划图片 1，护肤精华真实使用场景，自然光，干净克制的生活方式画面。','Xiaohongshu campaign image 1: a real-life skincare serum scene with natural light and a clean, restrained lifestyle aesthetic.'],
['天猫详情页护肤精华产品图 第七屏 · 实测对比，护肤精华真实使用场景，自然光，干净克制的生活方式画面。不包含产品。','Tmall skincare-serum product page, screen 7 · Test comparison. Real-life skincare setting, natural light, and a clean, restrained lifestyle aesthetic. Do not show the product.']
]);
const TERMS = [
['工作 Tab · Agent 抽屉与基础组件盘点','Work Tab · Agent Drawer & Base Component Inventory'],['工作 Tab · Agent 右侧抽屉盘点','Work Tab · Agent Right Drawer Inventory'],
['统计口径：工作 Tab 当前非 devHidden 任务','Scope: current non-devHidden tasks in the Work tab'],['排除：视频生成','Excluded: video generation'],['排除：报告生成','Excluded: report generation'],['包含：无产出抽屉的 Agent 标记','Included: Agents marked as having no output drawer'],
['统一抽屉外壳','Shared Drawer Shell'],['不属于任何 Agent，所有抽屉共享','Not owned by any Agent; shared by all drawers'],['关闭、类型、标题、状态、上一项/下一项、加宽','Close, type, title, status, previous/next, expand'],['Tab 文案、数量、激活态、动态显隐','Tab label, count, active state, and dynamic visibility'],['基础组件组合、独立滚动、空状态','Base component composition, independent scrolling, and empty state'],['批准、退回、评论、下载、生成等操作','Approve, return, comment, download, generate, and other actions'],
['逐 Agent 抽屉 Tab 清单','Drawer Tabs by Agent'],['精确到当前原型中的 Tab 名称','Uses the exact tab names in the current prototype'],['单独整理','Documented Separately'],['建议整合的基础组件','Recommended Base Components'],['建议复用内容结构与交互逻辑，共 11 个','Reuse the content structure and interaction logic across all 11 components'],['开发提示','Developer Note'],
['Agent × 基础组件复用矩阵','Agent × Base Component Reuse Matrix'],['从 Agent 视角查看 11 个基础组件的复用关系','View reuse across the 11 base components from each Agent’s perspective'],['Agent 基础组件组合预览','Agent Base Component Set Preview'],['请选择一个 Agent 查看组件组合','Select an Agent to view its component set'],
['文档内容（DocumentPanel）','Document Content (DocumentPanel)'],['图片画廊（ImageGalleryPanel）','Image Gallery (ImageGalleryPanel)'],['创意方向（CreativeDirectionPanel）','Creative Direction (CreativeDirectionPanel)'],['规划表（PlanPanel）','Plan (PlanPanel)'],['版本记录（VersionHistoryPanel）','Version History (VersionHistoryPanel)'],['状态结果（StatusResultPanel）','Status Result (StatusResultPanel)'],['相关提及（MentionListPanel）','Related Mentions (MentionListPanel)'],['邮件（EmailPanel）','Email (EmailPanel)'],['SEO 结构（SeoStructurePanel）','SEO Structure (SeoStructurePanel)'],['常见问题（FaqPanel）','FAQ (FaqPanel)'],['商品上架（ProductListingPanel）','Product Listing (ProductListingPanel)'],
['文档、正文等文本内容','Documents, body copy, and other text content'],['创意方向的编辑与参考图','Creative-direction editing and reference images'],['活动策划、详情页、推广计划共用','Shared by campaign planning, product pages, and promotion plans'],['版本 Tab 的统一实现','Shared implementation for the Version tab'],['一个基础组件，包含 2 种内容样式','One base component with two content variants'],['舆情相关提及','Social-listening related mentions'],['客户成功的邮件编辑与发送','Email editing and sending for Customer Success'],['SEO 结构与关键词','SEO structure and keywords'],['FAQ 编辑与排序','FAQ editing and ordering'],['商品上架的完整连续流程','Complete end-to-end product listing flow'],
['标题与正文','Title and body'],['查看与编辑','View and edit'],['自动保存','Autosave'],['方向标题','Direction title'],['创意说明','Creative brief'],['参考产品图','Reference product image'],['可展开计划','Expandable plans'],['计划字段详情','Plan field details'],['批量展开与收起','Expand and collapse all'],['版本号','Version number'],['更新时间','Updated'],['变更说明','Change notes'],['指标结果样式','Metric result variant'],['舆情发现样式','Sentiment finding variant'],['提及卡片','Mention cards'],['原文评论','Source comments'],['查看原文','View source'],['邮件列表','Email list'],['收件人、主题与正文','Recipient, subject, and body'],['草稿与发送状态','Draft and sent status'],['关键词','Keywords'],['标题结构','Heading structure'],['SEO 校验','SEO validation'],['问答条目','Q&A entries'],['增删排序','Add, delete, and reorder'],['保存状态','Save status'],['商品资料与 SKU','Product data and SKUs'],['字段校验','Field validation'],['平台回执与上架结果','Platform receipt and listing result'],
['内容生成 Agent','Content Generation Agent'],['活动策划 Agent','Campaign Planning Agent'],['详情页 Agent','Product Page Agent'],['推广计划 Agent','Promotion Planning Agent'],['客户成功 Agent','Customer Success Agent'],['数据分析 Agent','Data Analysis Agent'],['舆情监控 Agent','Social Listening Agent'],['店铺巡检 Agent','Store Audit Agent'],['商品上架 Agent','Product Listing Agent'],
['内容产出组合','Content Output Set'],['创意规划组合','Creative Planning Set'],['客户沟通组合','Customer Communication Set'],['状态洞察组合','Status Insight Set'],['商品上架组合','Product Listing Set'],
['右侧抽屉 Tab','Right Drawer Tabs'],['文档内容','Document Content'],['图片画廊','Image Gallery'],['创意方向','Creative Direction'],['当前活动策划','Current Campaign Plan'],['当前规划表','Current Plan'],['推广计划表','Promotion Plan'],['版本记录','Version History'],['状态结果','Status Result'],['相关提及','Related Mentions'],['商品上架','Product Listing'],['发现详情','Finding Details'],['常见问题','FAQ'],['正文','Body'],['文档','Document'],['图片','Images'],['邮件','Email'],['版本','Versions'],
['内容图片预览','Content Image Preview'],['详情页图片预览','Product Page Image Preview'],['推广图片预览','Promotion Image Preview'],['内容生成、B2B SEO','Content Generation, B2B SEO'],['详情页','Product Page'],['推广计划','Promotion Plan'],
['打开原图片画廊','Open original image gallery'],['查看文档内容组件样式','View Document Content component'],['查看创意方向样式','View Creative Direction style'],['查看规划表样式','View Plan style'],['查看版本记录样式','View Version History style'],['查看相关提及样式','View Related Mentions style'],['查看邮件样式','View Email style'],['查看 SEO 结构样式','View SEO Structure style'],['查看常见问题样式','View FAQ style'],['查看商品上架样式','View Product Listing style'],['的完整组件组合',' full component set'],['查看','View '],['样式',' style'],
['基础组件复用矩阵','Base Component Reuse Matrix'],['操作按钮','Action buttons'],['关闭抽屉','Close drawer'],['加宽','Expand'],['上一个方向','Previous direction'],['下一个方向','Next direction'],['上一篇','Previous'],['下一篇','Next'],['全部展开','Expand all'],['全部收起','Collapse all'],
['文档内容组件样式','Document Content component'],['图片画廊组件样式','Image Gallery component'],['创意方向组件样式','Creative Direction component'],['规划表样式','Plan component'],['版本记录组件样式','Version History component'],['状态结果指标样式','Status Result · Metrics'],['状态结果舆情样式','Status Result · Sentiment'],['相关提及组件样式','Related Mentions component'],['邮件样式','Email component'],['SEO 结构组件样式','SEO Structure component'],['常见问题组件样式','FAQ component'],['商品上架组件样式','Product Listing component'],
['社媒内容','Social Content'],['预算不多时，我反而更在意这 3 个护肤细节','With a limited budget, I care more about these three skincare details'],['标题','Title'],['内容','Content'],['详情图 · 9 张 · 上下拼起来就是整张详情页','Detail images · 9 images · Stack vertically for the full product page'],['看整页','View full page'],['首轮生成 · 3 个方向','Initial generation · 3 directions'],['方向一：成分证据先行','Direction 1: Lead with ingredient evidence'],['当前版本 · 采纳方向二后重写','Current version · Rewritten after adopting direction 2'],['参考产品图（仅限 1 张）','Reference product image (1 only)'],
['最近 7 天转化率变化说明与建议','Explanation and recommendations for the last 7 days’ conversion change'],['最近 7 天转化率分析','Last 7 Days Conversion Analysis'],['客户数据咨询','Customer Data Inquiry'],['起草规则：向客户说明转化率变化、判断依据和下一步建议。','Drafting rule: explain the conversion change, supporting rationale, and next steps to the customer.'],['收件人','To'],['抄送','Cc'],['主题','Subject'],['返回邮件列表','Back to email list'],['草稿','Draft'],
['文章结构','Article Structure'],['敏感肌精华怎么选：成分、浓度与耐受','How to Choose a Serum for Sensitive Skin: Ingredients, Concentration & Tolerance'],['敏感肌精华怎么选','Choosing a serum for sensitive skin'],['敏感肌精华推荐','Serum recommendations for sensitive skin'],['烟酰胺 敏感肌','Niacinamide · Sensitive skin'],['精华浓度怎么看','Understanding serum concentration'],['精华建立耐受','Building serum tolerance'],['主词','Primary'],['长尾','Long-tail'],['字数','Word count'],['内链','Internal links'],['关键词密度','Keyword density'],['语言','Language'],['评分','Score'],['个 H2',' H2 headings'],['篇',' articles'],['个',' items'],
['先判断你是“敏感”还是“敏感肌”','First determine whether your skin is temporarily reactive or chronically sensitive'],['三个最常见的踩坑成分','Three commonly problematic ingredients'],['浓度不是越高越好','Higher concentration is not always better'],['建立耐受的 4 周节奏','A four-week tolerance-building schedule'],['按预算给的选购清单','A budget-based shopping list'],['敏感肌应该如何选择精华？','How should sensitive skin choose a serum?'],['烟酰胺适合敏感肌使用吗？','Is niacinamide suitable for sensitive skin?'],['敏感肌建立耐受需要多久？','How long does sensitive skin take to build tolerance?'],['精华浓度越高，修护效果越好吗？','Does a higher serum concentration repair skin better?'],['敏感肌精华可以和其他功效产品叠加吗？','Can a sensitive-skin serum be layered with other treatment products?'],
['净销售额异常偏低','Net sales unusually low'],['实际净销售额','Actual net sales'],['预期范围','Expected range'],['为何标记：','Why flagged:'],['分析结论','Analysis'],['中风险','Medium risk'],['苗头','Early signal'],['来源：Digate','Source: Digate'],['数据日期：','Data date: '],['已超时 3 天 6 小时','Overdue by 3 days 6 hours'],
['个性化营养体验：服务跟进仍需优化','Personalized nutrition experience: follow-up still needs improvement'],['原文用户评论','Original user comments'],['智能分析','AI Analysis'],['自然提及','Organic mention'],['负面','Negative'],['我也注意到服务跟进这个问题。','I noticed the follow-up issue too.'],['想看后续一周的变化。','I would like to see what changes over the next week.'],['这条提及的原文链接待补充','The original link for this mention is pending'],['互动','Engagement '],['用户','User '],['高压打工人小周','Overworked Office Worker Zhou'],['力量训练阿杰','Strength Trainer Jie'],
['共 5 条计划','5 plans total'],['计划一','Plan 1'],['计划二','Plan 2'],['计划三','Plan 3'],['计划四','Plan 4'],['计划五','Plan 5'],['阶段目的','Stage objective'],['投放阶段','Delivery stage'],['购买人群阶段','Audience stage'],['投放时段','Delivery time'],['投放地域','Region'],['初始预算','Initial budget'],['自定义人群摘要','Custom audience summary'],['平台精选人群','Platform-selected audience'],['其他人群','Other audiences'],['广告标语','Ad tagline'],['广告创意方向','Creative direction'],['新客拉新阶段','New-customer acquisition'],['浅度兴趣阶段','Early interest'],['深度兴趣阶段','Deep interest'],
['外卖嗜辣一族拉新计划','Spicy Delivery Fans Acquisition Plan'],['社交饮酒一族拉新计划','Social Drinkers Acquisition Plan'],['液体孢子功效理解提速计划','Liquid Spore Benefit Education Plan'],['液体孢子品质加购催化计划','Liquid Spore Quality Add-to-Cart Plan'],['高意向人群决策加速计划','High-Intent Decision Acceleration Plan'],['火辣外卖后，直接喝的肠盾','After spicy delivery, drink your gut shield'],['喝酒聚餐前，来支液体孢子。','Before drinks and dinner, take a liquid-spore shot.'],['液体孢子，30分钟给肠胃上道盾','Liquid spores: shield your gut in 30 minutes'],['看得懂的品质，随手喝的肠道守护','Quality you can understand, gut care you can drink anywhere'],['肠胃不等人，现在下单现在守护','Your gut cannot wait—order now, protect now'],
['北京、上海、广州、深圳、杭州、成都等一二线及准一线核心城市','Beijing, Shanghai, Guangzhou, Shenzhen, Hangzhou, Chengdu, and other tier-1 and emerging tier-1 cities'],['北京、上海、广州、深圳、杭州、成都、南京、武汉等高消费核心城市','Beijing, Shanghai, Guangzhou, Shenzhen, Hangzhou, Chengdu, Nanjing, Wuhan, and other high-spending cities'],['全国重点一二线及准一线城市，优先覆盖近30天高转化区域','Key tier-1, tier-2, and emerging tier-1 cities nationwide, prioritizing areas with high conversion in the past 30 days'],['肠道健康养护人群；保健食品内容易感人群','Gut-health audiences; health-food content responders'],['职场肠胃调理族；本行业精选人群包','Workplace digestive-care audience; industry curated audience pack'],['保健食品类目行为品牌偏好人群；外食高频人群','Health-food category brand-affinity audience; frequent diners-out'],['淘天行业年度King消费者；内容易感人群','Taobao/Tmall annual top consumers; content-responsive audience'],['店铺深度浏览人群；近7天加购未购人群','Deep store browsers; added but did not purchase in 7 days'],['近15天浏览未购人群；收藏加购相似商品人群','Viewed but did not purchase in 15 days; saved/added similar products'],['保健食品类目高潜待转化人群；高价值品质消费者','High-potential health-food prospects; high-value quality shoppers'],['类目近三天收藏加购未购人群；高价值活跃消费者','Saved/added but did not purchase in 3 days; high-value active shoppers'],
['第一屏 · 首屏 KV','Screen 1 · Hero KV'],['第二屏 · 痛点引入','Screen 2 · Problem Setup'],['第三屏 · 核心卖点','Screen 3 · Core Benefits'],['第四屏 · 技术机制','Screen 4 · Technology'],['第五屏 · 使用场景','Screen 5 · Use Cases'],['第六屏 · 成分解析','Screen 6 · Ingredient Breakdown'],['第七屏 · 实测对比','Screen 7 · Test Comparison'],['第八屏 · 使用方法','Screen 8 · How to Use'],['第九屏 · 规格与购买','Screen 9 · Specifications & Purchase'],['详情页生成 · 天猫','Product Page Generation · Tmall'],['推广图片 · 天猫','Promotion Image · Tmall'],['屏 · 从上到下',' screens · top to bottom'],['这是买家实际滚动看到的顺序','This is the actual order shoppers see while scrolling'],['回到分屏','Back to individual screens'],['整页预览','Full-page preview'],['关闭整页预览','Close full-page preview'],
['调整素材','Adjust Creative'],['图片生成提示词','Image prompt'],['图片尺寸','Image size'],['生图模型','Image model'],['禁止项提示词','Negative prompt'],['参考图','Reference image'],['添加参考图','Add reference image'],['不包含产品','Product not included'],['用作参考图','Use as reference'],['已设为参考图','Set as reference image'],['下载图片','Download image'],['开始下载图片','Image download started'],['重新生成','Regenerate'],['已提交重新生成','Regeneration submitted'],['查看更多操作','View more actions'],['更多','More'],['关闭图片预览','Close image preview'],['图片预览样式','Image preview'],
['上架流程','Listing Flow'],['天猫上架回执','Tmall Listing Receipt'],['选择上架产品','Select product to list'],['已确认的上架商品','Confirmed listing products'],['商品字段验证','Validate product fields'],['平台回执截图','Platform receipt screenshot'],['商品上架结果','Product listing result'],['发布商品的所在类目','Product category for publication'],['商品品类','Product type'],['规格类型','Specification type'],['正常规格','Standard size'],['品牌','Brand'],['商品系列','Product line'],['美容护肤 / 精华','Beauty & Skincare / Serum'],['修护系列','Repair Series'],['修护安瓶精华','Repair Ampoule Serum'],['修护精华','Repair Serum'],['舒缓面霜','Soothing Cream'],['规格：','Size: '],['主图','Main image'],['素材库','Asset library'],['已确认','Confirmed'],['已选择','Selected'],['选择','Select'],['点击查看大图','Select to enlarge'],['点击查看完整回执截图','View full receipt screenshot'],['点击查看完整上架结果','View full listing result'],['商品已上架 · 点击查看大图','Product listed · Select to enlarge'],
['11:00-13:00及17:00-20:00中晚餐点餐前后，以及22:00-01:00深夜加班与夜宵黄金时段。','11:00–13:00 and 17:00–20:00 around lunch and dinner orders, plus the 22:00–01:00 late-work and late-night-snack window.'],['18-40岁、有社交应酬、商务出差、饮酒熬夜等行为的高价值年轻主力人群。','High-value adults aged 18–40 who socialize, travel for business, drink alcohol, or stay up late.'],['07:30-09:30通勤早餐时段、12:00-14:00午休浏览时段及20:00-23:00晚间内容消费高峰。','07:30–09:30 commute and breakfast, 12:00–14:00 lunch browsing, and the 20:00–23:00 evening content peak.'],['09:00-11:00、14:00-17:00理性决策时段，以及20:00-24:00居家浏览与加购高峰。','09:00–11:00 and 14:00–17:00 rational-decision windows, plus the 20:00–24:00 at-home browsing and add-to-cart peak.'],['10:00-12:00、18:00-22:00下单高峰，活动结束前4小时提高投放强度。','10:00–12:00 and 18:00–22:00 purchase peaks; increase delivery intensity during the final four hours of the campaign.'],
['结构与关键词','Structure & Keywords'],['数据分析、店铺巡检','Data Analysis, Store Audit'],['舆情监控','Social Listening'],['规划表','Plan'],['SEO 结构','SEO Structure'],['SEO 文章','SEO Article'],['价格','Price'],['舆情发现','Sentiment Finding'],['服务跟进','Service Follow-up'],['电商推广','E-commerce Promotion'],['精华','Serum'],['天猫','Tmall'],['整页','Full Page'],['截图',' screenshot'],['商品主图',' product main image'],['图片预览','Image preview'],['预览',' preview'],['条',' items'],[' 的',' · '],['的',''],
['今天 ','Today '],['小时前',' hours ago'],['封',' message'],['中文','中文'],['语言切换','Language switch']
].sort((a,b)=>b[0].length-a[0].length);

const hasHan = value => /[\u3400-\u9fff]/.test(value || '');
function translate(value){
  if(!value || !hasHan(value)) return value;
  const leading=value.match(/^\s*/)[0], trailing=value.match(/\s*$/)[0], core=value.slice(leading.length,value.length-trailing.length);
  if(EXACT.has(core)) return leading+EXACT.get(core)+trailing;
  let output=core;
  for(const [zh,en] of TERMS) output=output.split(zh).join(en);
  output=output.replaceAll('，',', ').replaceAll('。','.').replaceAll('；','; ').replaceAll('：',': ').replaceAll('（',' (').replaceAll('）',')').replaceAll('、',', ');
  return leading+output+trailing;
}
const attributes=['aria-label','title','placeholder','alt','data-title'];
let currentLanguage='zh', applying=false;
function translateTextNode(node){
  if(!node.parentElement || node.parentElement.closest('script,style,.language-switch')) return;
  if(hasHan(node.data)) node.__zhText=node.data;
  const source=node.__zhText;
  if(source && node.data!==translate(source)) node.data=translate(source);
}
function translateElement(element){
  if(!(element instanceof HTMLElement) || element.closest('.language-switch')) return;
  element.__zhAttrs ||= {};
  for(const attr of attributes){const value=element.getAttribute(attr);if(hasHan(value))element.__zhAttrs[attr]=value;const source=element.__zhAttrs[attr],next=source&&translate(source);if(next&&value!==next)element.setAttribute(attr,next);}
  if(element.matches('input,textarea,option')){if(hasHan(element.value))element.__zhValue=element.value;if(element.__zhValue)element.value=translate(element.__zhValue);}
}
function translateTree(root=document.body){
  applying=true;
  if(root.nodeType===Node.TEXT_NODE) translateTextNode(root);
  else if(root.nodeType===Node.ELEMENT_NODE){translateElement(root);const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))node.nodeType===Node.TEXT_NODE?translateTextNode(node):translateElement(node);}
  applying=false;
}
function restoreChinese(){
  applying=true;
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode())){if(node.nodeType===Node.TEXT_NODE&&node.__zhText!=null)node.data=node.__zhText;else if(node.nodeType===Node.ELEMENT_NODE){if(node.__zhAttrs)for(const [attr,value] of Object.entries(node.__zhAttrs))node.setAttribute(attr,value);if(node.__zhValue!=null)node.value=node.__zhValue;}}
  applying=false;
}
function updateSwitch(){document.querySelectorAll('.language-switch button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lang===currentLanguage)));}
function setLanguage(language,{remember=true}={}){
  if(!['zh','en'].includes(language))return;
  const comboIndex=[...document.querySelectorAll('#agent-combo-tabs [role="tab"]')].findIndex(button=>button.classList.contains('on'));
  currentLanguage=language;document.documentElement.lang=language==='en'?'en':'zh-CN';
  if(language==='en')translateTree();else{restoreChinese();if(activeAgentBundleKey&&comboIndex>=0)showAgentBundleTab(comboIndex);}
  document.title=language==='en'?'Work Tab · Agent Drawer & Base Component Inventory':'工作 Tab · Agent 抽屉与基础组件盘点';
  updateSwitch();if(remember)try{localStorage.setItem('drawer-inventory-language',language)}catch(_){}
}
document.querySelectorAll('.language-switch button').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));
new MutationObserver(records=>{if(applying||currentLanguage!=='en')return;for(const record of records){if(record.type==='childList')record.addedNodes.forEach(translateTree);else if(record.type==='characterData')translateTree(record.target);else translateElement(record.target);}}).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:attributes});
let saved='zh';try{saved=localStorage.getItem('drawer-inventory-language')||'zh'}catch(_){}setLanguage(saved,{remember:false});
})();
